name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Instalar dependencias
        run: |
          pip install pytest
          pip install pytest-bdd
          pip install pytest-cov

      - name: Ejecutar tests
        run: |
          pytest --cov=app --cov-fail-under=80